services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ChaptedTeam\Chapted\:
    resource: '../Classes/*'

  Google\Client:
    public: true

  ChaptedTeam\Chapted\Middlewares\GoogleFrontendLoginMiddleware:
    public: true
    arguments:
      $client: '@Google\Client'